service: serverless-aws-ts-starter

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 10 # 10 seconds timeout

# Functions
functions:
  getConfiguration:
    handler: src/functions/hello.handler
    events:
      - http: 
          path: hello
          method: post

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

# Custom tsconfig
custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'
